rss feeds:
    - https://lecturecapture.qut.edu.au/ess/feed?id=83c6d8c0-a3b4-430d-a7fe-bd0e437f9c4c&type=M4V

download directory: /Users/aidan/Dropbox/GitHub/EchoDownloader/downloads
sort into subject folders: yes
folder name within subject folder: Lecture Videos

high quality: yes
