rss feeds:
    - https://lecturecapture.qut.edu.au/ess/feed?id=8f63986c-d501-4220-bab1-aaa904397e9b&type=M4V
    - https://lecturecapture.qut.edu.au/ess/feed?id=7e1bce3d-b6a5-4f98-a5e0-fd89959061d3&type=M4V
    - https://lecturecapture.qut.edu.au/ess/feed?id=98b3c0f1-bd57-4085-959f-636fc79fc3cb&type=M4V
    - https://lecturecapture.qut.edu.au/ess/feed?id=780bf07b-3bad-4bef-abf9-783aa59f3665&type=M4V

download directory: /Users/aidan/Dropbox/Uni/2017/Semester2
sort into subject folders: yes
folder name within subject folder: Lecture Videos

high quality: no
